services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tipsterarena
      POSTGRES_USER: paul
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    secrets:
      - db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paul -d tipsterarena"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 tipsterarena.asgi:application
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://paul:${DATABASE_PASSWORD}@db:5432/tipsterarena
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: tipsterarena.settings
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
    secrets:
      - db-password

  npm:
    image: node:20-slim
    working_dir: /app
    command: sh -c "npm install && npm install vite && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      NODE_ENV: development

volumes:
  postgres_data:

secrets:
  db-password:
    file: db/password.txt 