# Generated by Django 5.2 on 2025-05-17 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='tip',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('followers', 'Followers')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='tip',
            name='bet_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('treble', 'Treble'), ('fourfold', 'Fourfold'), ('fivefold', 'Fivefold'), ('sixfold', 'Sixfold'), ('sevenfold', 'Sevenfold'), ('eightfold', 'Eightfold'), ('accumulator', 'Accumulator'), ('trixie', 'Trixie'), ('yankee', 'Yankee'), ('canadian', 'Canadian / Super Yankee'), ('patent', 'Patent'), ('lucky15', 'Lucky 15'), ('lucky31', 'Lucky 31'), ('lucky63', 'Lucky 63'), ('heinz', 'Heinz'), ('super_heinz', 'Super Heinz'), ('goliath', 'Goliath'), ('super_heinz_singles', 'Super Heinz with Singles'), ('super_goliath', 'Super Goliath')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='confidence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Confidence level (1-5 stars, optional)', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='each_way',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='tip',
            name='emojis',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='gif_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='gif_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_premium_tip',
            field=models.BooleanField(default=False, help_text='Is this a Premium Tip (only for Premium users)?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='odds',
            field=models.CharField(blank=True, help_text="The odds for the tip (e.g., '2.5' or '2/1')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='odds_format',
            field=models.CharField(blank=True, choices=[('decimal', 'Decimal'), ('fractional', 'Fractional')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='poll',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='premium_tip_posted_at',
            field=models.DateTimeField(blank=True, help_text='When this Premium Tip was posted.', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='premium_tip_views',
            field=models.IntegerField(default=0, help_text='Number of times this Premium Tip was viewed.'),
        ),
        migrations.AddField(
            model_name='tip',
            name='release_schedule',
            field=models.JSONField(default=dict, help_text='JSON mapping tier IDs to release times'),
        ),
        migrations.AddField(
            model_name='tip',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='scheduled_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('dead_heat', 'Dead Heat'), ('void_non_runner', 'Void/Non Runner')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tip',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('premium', 'Premium Users Only'), ('subscribers', 'All Subscribers'), ('tier_specific', 'Specific Tiers')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.CharField(choices=[('no_one', 'No one'), ('followers', 'Followers'), ('everyone', 'Everyone')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(default='@default', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_anniversary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_blazing_inferno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_crowd_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_crystal_ball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_football_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_hail_mary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_high_odds_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_hole_in_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_hoop_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_horse_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_hot_streak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_ice_cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_late_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_meme_lord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_rookie_rocket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_soccer_sniper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_streak_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_tips_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_tips_100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_tips_50',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_tipster_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_tipster_titan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_touchdown_tycoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_upset_oracle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_viral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_wicket_wizard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_win_rate_60',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_win_rate_75',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_winning_streak_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_badge_winning_streak_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_tipster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_top_tipster',
            field=models.BooleanField(default=False, help_text='Is this user a Top Tipster?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maximum_tier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='minimum_tier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_features',
            field=models.JSONField(default=dict, help_text='Features enabled for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', help_text='Current subscription tier for the user.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier_expiry',
            field=models.DateTimeField(blank=True, help_text='When the current paid tier expires.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipster_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipster_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipster_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_tipster_since',
            field=models.DateTimeField(blank=True, help_text='When the user became a Top Tipster.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_tips',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='Has the user used their free trial?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='win_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tip',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('golf', 'Golf'), ('tennis', 'Tennis'), ('horse_racing', 'Horse Racing'), ('american_football', 'American Football'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('boxing', 'Boxing'), ('cricket', 'Cricket'), ('cycling', 'Cycling'), ('darts', 'Darts'), ('gaelic_games', 'Gaelic Games'), ('greyhound_racing', 'Greyhound Racing'), ('motor_sport', 'Motor Sport'), ('rugby_union', 'Rugby Union'), ('snooker', 'Snooker'), ('volleyball', 'Volleyball')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/')),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.messagethread')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('related_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tip')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TipsterTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('max_subscribers', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('tip_release_delay', models.IntegerField(default=0, help_text='Minutes to delay tip release for this tier')),
                ('priority_access', models.BooleanField(default=False, help_text='Whether this tier gets immediate access to tips')),
                ('can_view_analysis', models.BooleanField(default=True)),
                ('can_view_history', models.BooleanField(default=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tipster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_tiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('tipster', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tip',
            name='allowed_tiers',
            field=models.ManyToManyField(blank=True, related_name='exclusive_tips', to='core.tipstertier'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.comment')),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tip', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.comment')),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tip', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='TipsterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('past_due', 'Past Due'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired')], default='incomplete', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipster_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.tipstertier')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('subscriber', 'tier')},
            },
        ),
    ]
