# Generated by Django 5.2.1 on 2025-05-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_bio_tip_audience_tip_bet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', help_text='Current subscription tier for the user.', max_length=10),
        ),
    ]
