# Generated by Django 5.2.2 on 2025-06-16 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_messagethread_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagethread',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='created_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='last_message',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
