# Generated by Django 5.2.2 on 2025-06-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_retweet',
            field=models.BooleanField(default=False, help_text='Is this tip a retweet?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='original_tip',
            field=models.ForeignKey(blank=True, help_text='Original tip if this is a retweet', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='core.tip'),
        ),
    ]
