# Generated by Django 5.2.1 on 2025-05-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Earnings for current month', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='revenue_share_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of premium revenue shared with this tipster', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total earnings from tips and revenue sharing', max_digits=10),
        ),
    ]
