# Generated by Django 5.2.2 on 2025-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tip_is_retweet_tip_original_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_used',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('premium', 'Premium')], default='premium', help_text='Current subscription tier for the user.', max_length=10),
        ),
    ]
