# Generated by Django 5.1.6 on 2025-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_messagethread_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="audience",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("followers", "Followers")],
                default="everyone",
                max_length=20,
            ),
        ),
    ]
