# Generated by Django 5.2.2 on 2025-06-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_trial_used_field'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_userprofile DROP COLUMN IF EXISTS trial_used;"
        ),
    ]
