# Generated by Django 5.2.1 on 2025-06-15 19:43

from django.conf import settings
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_share_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL
            """
            ALTER TABLE core_share DROP CONSTRAINT IF EXISTS core_share_user_id_tip_id_comment_id_uniq;
            ALTER TABLE core_share DROP COLUMN IF EXISTS comment_id;
            ALTER TABLE core_share ADD CONSTRAINT core_share_user_id_tip_id_uniq UNIQUE (user_id, tip_id);
            """,
            # Reverse SQL
            """
            ALTER TABLE core_share DROP CONSTRAINT IF EXISTS core_share_user_id_tip_id_uniq;
            ALTER TABLE core_share ADD COLUMN comment_id integer NULL;
            ALTER TABLE core_share ADD CONSTRAINT core_share_user_id_tip_id_comment_id_uniq UNIQUE (user_id, tip_id, comment_id);
            """
        ),
    ]
