# Generated by Django 5.1.6 on 2025-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
    ]
