# Generated by Django 5.1.6 on 2025-03-12 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_comment_parent_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="share",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.comment",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.tip",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="tip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="core.tip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "tip", "comment")},
        ),
        migrations.AlterUniqueTogether(
            name="share",
            unique_together={("user", "tip", "comment")},
        ),
    ]
