# Generated by Django 5.1.6 on 2025-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_like_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="emojis",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
        migrations.AddField(
            model_name="tip",
            name="gif",
            field=models.FileField(blank=True, null=True, upload_to="gifs/"),
        ),
        migrations.AddField(
            model_name="tip",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tips/"),
        ),
        migrations.AddField(
            model_name="tip",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tip",
            name="poll",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
        migrations.AddField(
            model_name="tip",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
