# Generated by Django 5.1.6 on 2025-03-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_tip_emojis_tip_gif_tip_image_tip_location_tip_poll_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("url", models.URLField(unique=True)),
            ],
            options={
                "unique_together": {("date", "venue")},
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=10)),
                ("horse", models.CharField(max_length=100)),
                ("jockey", models.CharField(max_length=100)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.racemeeting",
                    ),
                ),
            ],
        ),
    ]
