# Generated by Django 5.1.6 on 2025-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_racemeeting_raceresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="gif",
        ),
        migrations.AddField(
            model_name="tip",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
