# Generated by Django 5.1.6 on 2025-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_tip_gif_tip_gif_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="gif_height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tip",
            name="gif_width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
