# Generated by Django 5.1.6 on 2025-03-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_tip_gif_height_tip_gif_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comments/"),
        ),
    ]
