# Generated by Django 5.1.6 on 2025-03-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_comment_gif_url_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allow_messages",
            field=models.CharField(
                choices=[
                    ("no_one", "No one"),
                    ("followers", "Followers"),
                    ("everyone", "Everyone"),
                ],
                default="everyone",
                help_text="Who can send you message requests",
                max_length=20,
            ),
        ),
    ]
