# Generated by Django 5.1.6 on 2025-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_userprofile_allow_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="messages/"),
        ),
    ]
