# Generated by Django 5.1.6 on 2025-03-30 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_message_gif_url_message_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_tips", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
