# Generated by Django 5.1.7 on 2025-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_tip_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="bet_type",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("double", "Double"),
                    ("treble", "Treble"),
                    ("fourfold", "Fourfold"),
                    ("fivefold", "Fivefold"),
                    ("sixfold", "Sixfold"),
                    ("sevenfold", "Sevenfold"),
                    ("eightfold", "Eightfold"),
                    ("accumulator", "Accumulator"),
                    ("trixie", "Trixie"),
                    ("yankee", "Yankee"),
                    ("canadian", "Canadian / Super Yankee"),
                    ("patent", "Patent"),
                    ("lucky15", "Lucky 15"),
                    ("lucky31", "Lucky 31"),
                    ("lucky63", "Lucky 63"),
                    ("heinz", "Heinz"),
                    ("super_heinz", "Super Heinz"),
                    ("goliath", "Goliath"),
                    ("super_heinz_singles", "Super Heinz with Singles"),
                    ("super_goliath", "Super Goliath"),
                ],
                default="single",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tip",
            name="conditions",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tip",
            name="odds",
            field=models.CharField(default="1.0", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tip",
            name="odds_format",
            field=models.CharField(
                choices=[("decimal", "Decimal"), ("fractional", "Fractional")],
                default="decimal",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tip",
            name="resolution_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tip",
            name="stake",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("won", "Won"), ("lost", "Lost")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tip",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_tips",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="win_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="wins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
