# Generated by Django 5.1.7 on 2025-04-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_tip_bet_type_tip_conditions_tip_odds_tip_odds_format_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="conditions",
        ),
        migrations.AddField(
            model_name="tip",
            name="each_way",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("win", "Win"),
                    ("loss", "Loss"),
                    ("dead_heat", "Dead Heat"),
                    ("void_non_runner", "Void/Non Runner"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
