# Generated by Django 5.1.7 on 2025-04-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_tip_conditions_tip_each_way_alter_tip_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="stake",
        ),
        migrations.AddField(
            model_name="tip",
            name="confidence",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                help_text="Confidence level (1-5 stars, optional)",
                null=True,
            ),
        ),
    ]
