# Generated by Django 5.1.7 on 2025-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_raceresult_horse_remove_raceresult_jockey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('match_date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('pre', 'Pre'), ('in', 'In'), ('post', 'Post')], default='pre', max_length=20)),
                ('home_score', models.CharField(blank=True, max_length=10, null=True)),
                ('away_score', models.CharField(blank=True, max_length=10, null=True)),
                ('status_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['match_date', 'league'], name='core_footba_match_d_c820a8_idx')],
            },
        ),
    ]
