# Generated by Django 5.1.7 on 2025-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_footballfixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfixture',
            name='key_events',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballfixture',
            name='odds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
