# Generated by Django 5.1.7 on 2025-04-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_footballevent_footballleague_footballteam_teamstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('par', models.CharField(default='N/A', max_length=10)),
                ('yardage', models.CharField(default='N/A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GolfPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('world_ranking', models.CharField(default='N/A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GolfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏌️\u200d♂️', max_length=10)),
                ('priority', models.PositiveIntegerField(default=999)),
            ],
        ),
        migrations.CreateModel(
            name='GolfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('pre', 'Pre'), ('in', 'In Progress'), ('post', 'Post'), ('unknown', 'Unknown')], default='pre', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('venue', models.CharField(default='Location TBD', max_length=200)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('state_location', models.CharField(default='Unknown', max_length=100)),
                ('purse', models.CharField(default='N/A', max_length=20)),
                ('broadcast', models.CharField(default='N/A', max_length=100)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('total_rounds', models.PositiveIntegerField(default=4)),
                ('is_playoff', models.BooleanField(default=False)),
                ('weather_condition', models.CharField(default='N/A', max_length=100)),
                ('weather_temperature', models.CharField(default='N/A', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.golfcourse')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.golftour')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='N/A', max_length=10)),
                ('score', models.CharField(default='N/A', max_length=10)),
                ('rounds', models.JSONField(default=list)),
                ('strokes', models.CharField(default='N/A', max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='core.golfevent')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='core.golfplayer')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
    ]
