# Generated by Django 5.1.7 on 2025-04-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_golfcourse_golfplayer_golftour_golfevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('state', models.CharField(choices=[('pre', ' wPre'), ('in', 'In Progress'), ('post', 'Post'), ('unknown', 'Unknown')], default='pre', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('score', models.CharField(default='TBD', max_length=50)),
                ('sets', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('clock', models.CharField(default='0:00', max_length=20)),
                ('period', models.PositiveIntegerField(default=0)),
                ('round_name', models.CharField(default='Unknown Round', max_length=100)),
                ('match_type', models.CharField(default='Unknown', max_length=50)),
                ('player1_rank', models.CharField(default='N/A', max_length=10)),
                ('player2_rank', models.CharField(default='N/A', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TennisLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🎾', max_length=10)),
                ('priority', models.PositiveIntegerField(default=999)),
            ],
        ),
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('world_ranking', models.CharField(default='N/A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TennisVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('court', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TennisBettingOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_odds', models.CharField(default='N/A', max_length=20)),
                ('player2_odds', models.CharField(default='N/A', max_length=20)),
                ('provider', models.CharField(default='Unknown Provider', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='core.tennisevent')),
            ],
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_events', to='core.tennisplayer'),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_events', to='core.tennisplayer'),
        ),
        migrations.CreateModel(
            name='TennisTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.tennisleague')),
            ],
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tennistournament'),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.tennisvenue'),
        ),
        migrations.AddIndex(
            model_name='tennisevent',
            index=models.Index(fields=['date', 'state'], name='core_tennis_date_0579f7_idx'),
        ),
        migrations.AddIndex(
            model_name='tennisevent',
            index=models.Index(fields=['tournament'], name='core_tennis_tournam_bc0683_idx'),
        ),
    ]
