# Generated by Django 5.1.7 on 2025-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tennisevent_tennisleague_tennisplayer_tennisvenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisevent',
            name='state',
            field=models.CharField(choices=[('pre', 'Pre'), ('in', 'In Progress'), ('post', 'Post'), ('unknown', 'Unknown')], default='pre', max_length=20),
        ),
    ]
