# Generated by Django 5.1.7 on 2025-04-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_tennisevent_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('colour', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('breeder', models.CharField(blank=True, max_length=100, null=True)),
                ('dam', models.CharField(blank=True, max_length=100, null=True)),
                ('dam_region', models.CharField(blank=True, max_length=50, null=True)),
                ('sire', models.CharField(blank=True, max_length=100, null=True)),
                ('sire_region', models.CharField(blank=True, max_length=50, null=True)),
                ('grandsire', models.CharField(blank=True, max_length=100, null=True)),
                ('damsire', models.CharField(blank=True, max_length=100, null=True)),
                ('damsire_region', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jockey_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('course_id', 'region')},
            },
        ),
        migrations.CreateModel(
            name='HorseRacingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.horseracingcourse')),
            ],
            options={
                'unique_together': {('date', 'course')},
            },
        ),
        migrations.CreateModel(
            name='HorseRacingRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(unique=True)),
                ('off_time', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('distance_round', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_f', models.FloatField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('race_class', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('age_band', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_band', models.CharField(blank=True, max_length=50, null=True)),
                ('prize', models.CharField(blank=True, max_length=50, null=True)),
                ('field_size', models.IntegerField(blank=True, null=True)),
                ('going', models.CharField(blank=True, max_length=50, null=True)),
                ('rail_movements', models.CharField(blank=True, max_length=255, null=True)),
                ('stalls', models.CharField(blank=True, max_length=50, null=True)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('surface', models.CharField(blank=True, max_length=50, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='core.horseracingmeeting')),
            ],
            options={
                'unique_together': {('meeting', 'off_time', 'race_id')},
            },
        ),
        migrations.CreateModel(
            name='RaceRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('headgear', models.CharField(blank=True, max_length=50, null=True)),
                ('headgear_first', models.CharField(blank=True, max_length=50, null=True)),
                ('lbs', models.IntegerField(blank=True, null=True)),
                ('official_rating', models.IntegerField(blank=True, null=True)),
                ('rpr', models.IntegerField(blank=True, null=True)),
                ('topspeed', models.IntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('last_run', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer_rtf', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer_14_days_runs', models.IntegerField(blank=True, null=True)),
                ('trainer_14_days_wins', models.IntegerField(blank=True, null=True)),
                ('trainer_14_days_percent', models.IntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('spotlight', models.TextField(blank=True, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='core.horse')),
                ('jockey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runners', to='core.jockey')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='core.horseracingrace')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runners', to='core.trainer')),
            ],
            options={
                'unique_together': {('race', 'horse')},
            },
        ),
        migrations.CreateModel(
            name='RunnerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('race_id', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('distance_f', models.FloatField(blank=True, null=True)),
                ('distance_y', models.IntegerField(blank=True, null=True)),
                ('quote', models.TextField()),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.racerunner')),
            ],
        ),
        migrations.CreateModel(
            name='HorseRacingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('ovr_btn', models.FloatField(blank=True, null=True)),
                ('btn', models.FloatField(blank=True, null=True)),
                ('lbs', models.IntegerField(blank=True, null=True)),
                ('headgear', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('decimal_time', models.FloatField(blank=True, null=True)),
                ('prize', models.CharField(blank=True, max_length=50, null=True)),
                ('official_rating', models.IntegerField(blank=True, null=True)),
                ('rpr', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.horse')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.horseracingrace')),
                ('jockey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.jockey')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.trainer')),
            ],
            options={
                'unique_together': {('race', 'horse')},
            },
        ),
    ]
