# Generated by Django 5.1.7 on 2025-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_horse_jockey_trainer_horseracingcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='horse_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
