# Generated by Django 5.1.7 on 2025-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_horse_horse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey',
            name='jockey_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
