# Generated by Django 5.1.7 on 2025-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_jockey_jockey_id_alter_trainer_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseracingresult',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
