# Generated by Django 5.2 on 2025-04-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_userprofile_full_name_userprofile_kyc_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
