# Generated by Django 5.2 on 2025-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='bet_type',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('treble', 'Treble'), ('fourfold', 'Fourfold'), ('fivefold', 'Fivefold'), ('sixfold', 'Sixfold'), ('sevenfold', 'Sevenfold'), ('eightfold', 'Eightfold'), ('accumulator', 'Accumulator'), ('trixie', 'Trixie'), ('yankee', 'Yankee'), ('canadian', 'Canadian / Super Yankee'), ('patent', 'Patent'), ('lucky15', 'Lucky 15'), ('lucky31', 'Lucky 31'), ('lucky63', 'Lucky 63'), ('heinz', 'Heinz'), ('super_heinz', 'Super Heinz'), ('goliath', 'Goliath'), ('super_heinz_singles', 'Super Heinz with Singles'), ('super_goliath', 'Super Goliath')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='odds',
            field=models.CharField(blank=True, help_text="The odds for the tip (e.g., '2.5' or '2/1')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='odds_format',
            field=models.CharField(blank=True, choices=[('decimal', 'Decimal'), ('fractional', 'Fractional')], max_length=20, null=True),
        ),
    ]
