# Generated by Django 5.2 on 2025-04-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_tip_bet_type_alter_tip_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyevent',
            name='assist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
