# Generated by Django 5.2 on 2025-05-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_keyevent_assist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horseracingcourse',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='racerunner',
            options={'ordering': ['number']},
        ),
        migrations.AlterUniqueTogether(
            name='horseracingcourse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='racerunner',
            unique_together={('race', 'number')},
        ),
        migrations.AddField(
            model_name='horseracingcourse',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='horseracingcourse',
            name='surface',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='horseracingcourse',
            name='track_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='racerunner',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horse'),
        ),
        migrations.AlterField(
            model_name='racerunner',
            name='jockey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jockey'),
        ),
        migrations.AlterField(
            model_name='racerunner',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racerunner',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
        ),
        migrations.RemoveField(
            model_name='horseracingcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='horseracingcourse',
            name='region',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='form',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='headgear',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='headgear_first',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='lbs',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='official_rating',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='rpr',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='spotlight',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='topspeed',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='trainer_14_days_percent',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='trainer_14_days_runs',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='trainer_14_days_wins',
        ),
        migrations.RemoveField(
            model_name='racerunner',
            name='trainer_rtf',
        ),
        migrations.CreateModel(
            name='HorseRacingBettingOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='core.racerunner')),
            ],
            options={
                'ordering': ['bookmaker', '-updated_at'],
                'unique_together': {('runner', 'bookmaker')},
            },
        ),
    ]
