# Generated by Django 5.2 on 2025-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_horseracingcourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingcourse',
            name='course_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='horseracingcourse',
            name='surface',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='horseracingcourse',
            name='track_type',
            field=models.CharField(max_length=50),
        ),
    ]
