# Generated by Django 5.2 on 2025-05-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_horseracingcourse_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseracingcourse',
            name='region',
            field=models.CharField(default='GB', max_length=10),
        ),
    ]
