# Generated by Django 5.2 on 2025-05-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_horseracingcourse_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerunner',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='headgear',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='headgear_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='last_run',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='lbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='official_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='rpr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='spotlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='topspeed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='trainer_14_days_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='trainer_14_days_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='trainer_14_days_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='racerunner',
            name='trainer_rtf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
