# Generated by Django 5.2 on 2025-05-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_racerunner_comment_racerunner_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfplayer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='golfplayer',
            name='player_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='golfplayer',
            name='world_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
