# Generated by Django 5.2 on 2025-05-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_update_golf_player'),
        ('core', '0042_golfplayer_country_golfplayer_player_id_and_more'),
    ]

    operations = [
    ]
