# Generated by Django 5.2 on 2025-05-04 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_fix_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, db_table='core_tip_bookmarks', related_name='bookmarked_tips', to=settings.AUTH_USER_MODEL),
        ),
    ]
