# Generated by Django 5.2 on 2025-05-05 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_tip_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='golfscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='round',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='player',
        ),
        migrations.RemoveField(
            model_name='golftournament',
            name='defending_champion',
        ),
        migrations.RemoveField(
            model_name='golftournament',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='golfevent',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='footballevent',
            name='away_stats',
        ),
        migrations.RemoveField(
            model_name='footballevent',
            name='home_stats',
        ),
        migrations.AddField(
            model_name='footballevent',
            name='away_team_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team_event', to='core.teamstats'),
        ),
        migrations.AddField(
            model_name='footballevent',
            name='home_team_stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team_event', to='core.teamstats'),
        ),
        migrations.AddField(
            model_name='golfevent',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.golftour'),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_events', to='core.footballteam'),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_events', to='core.footballteam'),
        ),
        migrations.AlterField(
            model_name='footballevent',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.footballleague'),
        ),
        migrations.AlterField(
            model_name='golfevent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.golfcourse'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GolfRound',
        ),
        migrations.DeleteModel(
            name='GolfScore',
        ),
        migrations.DeleteModel(
            name='GolfTournament',
        ),
    ]
