# Generated by Django 5.2 on 2025-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_golfscore_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyevent',
            name='is_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
