# Generated by Django 5.2 on 2025-05-05 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_keyevent_is_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('surface_stats', models.JSONField(default=dict)),
                ('tournament_stats', models.JSONField(default=dict)),
                ('head_to_head', models.JSONField(default=dict)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tennistournament',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='court_conditions',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='point_by_point',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='service_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='tiebreak_sets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='weather',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tennisevent',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='core.tennisplayer'),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='draw_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='prize_money',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='surface',
            field=models.CharField(choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass'), ('carpet', 'Carpet')], default='hard', max_length=20),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='tournament_type',
            field=models.CharField(choices=[('grand_slam', 'Grand Slam'), ('masters', 'Masters 1000'), ('atp_500', 'ATP 500'), ('atp_250', 'ATP 250'), ('wta_1000', 'WTA 1000'), ('wta_500', 'WTA 500'), ('wta_250', 'WTA 250')], default='atp_250', max_length=50),
        ),
        migrations.AddField(
            model_name='tennistournament',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tennisevent',
            index=models.Index(fields=['winner'], name='core_tennis_winner__35fb67_idx'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.tennisplayer'),
        ),
    ]
