# Generated by Django 5.2 on 2025-05-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_tennisplayerstats_alter_tennistournament_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(help_text='Your unique handle starting with @ (e.g., @username)', max_length=15, unique=True),
        ),
    ]
