# Generated by Django 5.2 on 2025-05-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_tipstersubscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='required_tier',
        ),
        migrations.RemoveField(
            model_name='tipstertier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tipstertier',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tip',
            name='allowed_tiers',
            field=models.ManyToManyField(blank=True, related_name='exclusive_tips', to='core.tipstertier'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='release_schedule',
            field=models.JSONField(default=dict, help_text='JSON mapping tier IDs to release times'),
        ),
        migrations.AddField(
            model_name='tip',
            name='scheduled_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipstertier',
            name='can_view_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipstertier',
            name='can_view_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipstertier',
            name='priority_access',
            field=models.BooleanField(default=False, help_text='Whether this tier gets immediate access to tips'),
        ),
        migrations.AddField(
            model_name='tipstertier',
            name='tip_release_delay',
            field=models.IntegerField(default=0, help_text='Minutes to delay tip release for this tier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_features',
            field=models.JSONField(default=dict, help_text='Features enabled for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipster_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tip',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('premium', 'Premium Users Only'), ('subscribers', 'All Subscribers'), ('tier_specific', 'Specific Tiers')], default='public', max_length=20),
        ),
    ]
