# Generated by Django 5.2 on 2025-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_userprofile_has_badge_anniversary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_premium_tip',
            field=models.BooleanField(default=False, help_text='Is this a Premium Tip (only for Premium users)?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='premium_tip_posted_at',
            field=models.DateTimeField(blank=True, help_text='When this Premium Tip was posted.', null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='premium_tip_views',
            field=models.IntegerField(default=0, help_text='Number of times this Premium Tip was viewed.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_top_tipster',
            field=models.BooleanField(default=False, help_text='Is this user a Top Tipster?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', help_text='Current subscription tier for the user.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier_expiry',
            field=models.DateTimeField(blank=True, help_text='When the current paid tier expires.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_tipster_since',
            field=models.DateTimeField(blank=True, help_text='When the user became a Top Tipster.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='Has the user used their free trial?'),
        ),
    ]
