# Generated by Django 5.2 on 2025-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='sport',
            field=models.CharField(choices=[('football', 'Football'), ('golf', 'Golf'), ('tennis', 'Tennis'), ('horse_racing', 'Horse Racing'), ('american_football', 'American Football'), ('baseball', 'Baseball'), ('basketball', 'Basketball'), ('boxing', 'Boxing'), ('cricket', 'Cricket'), ('cycling', 'Cycling'), ('darts', 'Darts'), ('gaelic_games', 'Gaelic Games'), ('greyhound_racing', 'Greyhound Racing'), ('motor_sport', 'Motor Sport'), ('rugby_union', 'Rugby Union'), ('snooker', 'Snooker'), ('volleyball', 'Volleyball')], max_length=20),
        ),
    ]
