"""
Django settings for tipsterarena project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.conf.urls.static import static
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-or8ih)*8^-c_@9h4r&sojeg#*5841-k%f9s+$tj##9n=&thm)4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'core.apps.CoreConfig',
    'rest_framework',  
    "csp",  
    "django_vite",  
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "tipsterarena.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'], 
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'core.context_processors.suggested_tipsters',  # Custom context processor
            ],
        },
    },
]

WSGI_APPLICATION = "tipsterarena.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# For development, add this to serve media files
# Security settings (optional, adjust as needed)
DEBUG = True  # Ensure this is True for development to serve media files

# Authentication settings
LOGIN_REDIRECT_URL = '/home/'  # After login
LOGOUT_REDIRECT_URL = '/'      # After logout
LOGIN_URL = '/'                # Redirect to landing if not authenticated


# CSP Settings
CSP_DEFAULT_SRC = ("'self'",)  # Only allow resources from the same origin by default
CSP_SCRIPT_SRC = (
    "'unsafe-inline'",  # Allow inline scripts (temporary, we'll address this later)
)
CSP_STYLE_SRC = (
    "'self'",  # Allow styles from your domain
    "https://cdnjs.cloudflare.com",  # Font Awesome
    "https://fonts.googleapis.com",  # Google Fonts
    "'unsafe-inline'",  # Allow inline styles (if any)
)
CSP_FONT_SRC = (
    "'self'",
    "https://fonts.googleapis.com",
    "https://fonts.gstatic.com",  # Google Fonts often loads font files from here
)
CSP_IMG_SRC = (
    "'self'",
    "data:",  # Allow data URIs (e.g., for small inline images)
)
CSP_CONNECT_SRC = ("'self'",)  # For APIs, WebSockets, etc.
CSP_FRAME_SRC = ("'none'",)  # Disallow iframes
CSP_OBJECT_SRC = ("'none'",)  # Disallow <object>, <embed>, etc.

CSP_REPORT_ONLY = True
CSP_REPORT_URI = "/csp-report/"  # Endpoint to receive violation reports

DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'dev_server_port': 3000,
        'static_url_prefix': '',  # Empty to avoid prepending 'dist'
        'manifest_path': BASE_DIR / 'static/dist/manifest.json',
    }
}